### ISSUE TITLE
[Minor] Mod Updates everytime you launch the game.

### ISSUE THREAD

**Issue by Kanzaji** [aleksander-ciesielski/isaac-stats-plus#5]
Hey there!

## Bug Descirption
Each time I launch the game, the mod updates itself. I doubt there are updates to the mod every second, tho that would be impressive😄

## Expected behaviour
Mod not updating on each startup, as that takes from 5 to 15 seconds, and possibly longer on low-end machines.

## Logs
~~[log.txt](https://github.com/aleksander-ciesielski/isaac-stats-plus/files/13758583/log.txt)~~
Reuploaded to gist: https://gist.github.com/Kanzaji/f3e86f0f2a9b22316c910263cb6018bd
I do have a lot of mods, some of them are for memes installed by my friend and disabled, and if requested I can try reproducing the issue without any other mods installed (I just hope that won't remove my mod data and disable/enable list >.>)

**Comment by aleksander-ciesielski** [comment]
hey, thanks for reporting the issue 🤗

from the logs, I see that you still have the old damage multiplier stat mod - this is because I renamed the mod to Stats+, but Steam didn't handle it nicely, and instead of upgrading the damage multiplier stat to Stats+, it simply installs it on top of the old one. could you please try removing the "damage-multiplier-stat_2729900570" from the mods folder? and if it doesn't help, you could also try reinstalling the whole game (saves should be in the cloud, so you won't lose anything I believe).

**Comment by Kanzaji** [comment]
Yup, that indeed worked ❤️ Was suspecting this to be the issue, tho preffered to report it anyway 😄
Any ideas / intents to fix it automatically? I saw few comments on the steam page about this issue, so it might be worth resolving in the background than forcing users to manually remove the old files.

**Comment by aleksander-ciesielski** [comment]
it would be great to somehow fix it automatically although I don't see any way to do so. I guess the only thing I can do is to create an FAQ section that will mention the issue & tell the ppl to delete the old mod.
